export const containerTypes = {
  FLEX_HORIZONTAL: 'FLEX_HORIZONTAL',
  FLEX_VERTICAL: 'FLEX_VERTICAL',
  BORDER_ANIMATED: 'BORDER_ANIMATED',
  LAYOUT: 'LAYOUT',
  EXERCICES_SELECTORS: 'EXERCICES_SELECTORS',
  BLUR_LAYER: 'BLUR_LAYER',
};
